const dummyData = {
  categories: [
    { name: "Burgers", description: "Juicy grilled burgers" },
    { name: "Pizzas", description: "Oven-baked cheesy pizzas" },
    { name: "Burritos", description: "Rolled Mexican delights" },
    { name: "Sandwiches", description: "Stacked and stuffed sandwiches" },
    { name: "Wraps", description: "Rolled up wraps packed with flavor" },
    { name: "Bowls", description: "Balanced rice and protein bowls" },
  ],

  customizations: [
    // Toppings
    { name: "Extra Cheese", price: 25, type: "topping" },
    { name: "Jalapeños", price: 20, type: "topping" },
    { name: "Onions", price: 10, type: "topping" },
    { name: "Olives", price: 15, type: "topping" },
    { name: "Mushrooms", price: 18, type: "topping" },
    { name: "Tomatoes", price: 10, type: "topping" },
    { name: "Bacon", price: 30, type: "topping" },
    { name: "Avocado", price: 35, type: "topping" },

    // Sides
    { name: "Coke", price: 30, type: "side" },
    { name: "Fries", price: 35, type: "side" },
    { name: "Garlic Bread", price: 40, type: "side" },
    { name: "Chicken Nuggets", price: 50, type: "side" },
    { name: "Iced Tea", price: 28, type: "side" },
    { name: "Salad", price: 33, type: "side" },
    { name: "Potato Wedges", price: 38, type: "side" },
    { name: "Mozzarella Sticks", price: 45, type: "side" },
    { name: "Sweet Corn", price: 25, type: "side" },
    { name: "Choco Lava Cake", price: 42, type: "side" },
  ],
  // menu : [
  //   {
  //     name: "Classic Cheeseburger",
  //     description: "Grilled beef patty, cheese, lettuce, tomato, and pickles",
  //     image_url: "https://images.unsplash.com/photo-1550547660-d9450f859349",
  //     price: 8.99,
  //     rating: 4.5,
  //     calories: 750,
  //     protein: 30,
  //     category_name: "Burgers",
  //     customizations: ["Extra Cheese", "No Onions", "Gluten-Free Bun"]
  //   },
  //   {
  //     name: "Pepperoni Pizza",
  //     description: "Classic pepperoni, mozzarella cheese, and tomato sauce",
  //     image_url: "https://images.unsplash.com/photo-1601924638867-3ec4f4c5fe47",
  //     price: 12.5,
  //     rating: 4.7,
  //     calories: 900,
  //     protein: 35,
  //     category_name: "Pizzas",
  //     customizations: ["Extra Pepperoni", "Stuffed Crust", "No Cheese"]
  //   },
  //   {
  //     name: "Bean Burrito",
  //     description: "Spicy black beans, rice, cheese, and salsa in a tortilla",
  //     image_url: "https://images.unsplash.com/photo-1613145993562-6e1fef9926df",
  //     price: 7.25,
  //     rating: 4.3,
  //     calories: 600,
  //     protein: 22,
  //     category_name: "Wraps",
  //     customizations: ["Add Avocado", "Spicy Salsa", "No Cheese"]
  //   },
  //   {
  //     name: "BBQ Bacon Burger",
  //     description: "Beef patty, BBQ sauce, bacon, and cheddar cheese",
  //     image_url: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90",
  //     price: 9.75,
  //     rating: 4.6,
  //     calories: 850,
  //     protein: 32,
  //     category_name: "Burgers",
  //     customizations: ["Add Jalapeños", "No Bacon", "Extra BBQ Sauce"]
  //   },
  //   {
  //     name: "Chicken Caesar Wrap",
  //     description: "Grilled chicken, romaine, Caesar dressing, and parmesan",
  //     image_url: "https://images.unsplash.com/photo-1601050690185-965d6fa7ab5c",
  //     price: 8.25,
  //     rating: 4.4,
  //     calories: 650,
  //     protein: 28,
  //     category_name: "Wraps",
  //     customizations: ["Whole Wheat Wrap", "Extra Dressing", "No Cheese"]
  //   },
  //   {
  //     name: "Grilled Veggie Sandwich",
  //     description: "Grilled zucchini, peppers, and hummus on whole grain bread",
  //     image_url: "https://images.unsplash.com/photo-1568600891621-2ec607a1cf1f",
  //     price: 7.75,
  //     rating: 4.2,
  //     calories: 550,
  //     protein: 18,
  //     category_name: "Sandwiches",
  //     customizations: ["Add Cheese", "No Onions", "Extra Hummus"]
  //   },
  //   {
  //     name: "Double Patty Burger",
  //     description: "Two beef patties, cheese, lettuce, and tomato",
  //     image_url: "https://images.unsplash.com/photo-1603048290964-dfbb3d03f993",
  //     price: 10.5,
  //     rating: 4.8,
  //     calories: 1100,
  //     protein: 45,
  //     category_name: "Burgers",
  //     customizations: ["Triple Patty", "No Cheese", "Add Bacon"]
  //   },
  //   {
  //     name: "Paneer Tikka Wrap",
  //     description: "Spiced paneer, onions, and bell peppers in a wrap",
  //     image_url: "https://images.unsplash.com/photo-1619250408830-96f18f1ecbd0",
  //     price: 8.0,
  //     rating: 4.5,
  //     calories: 620,
  //     protein: 26,
  //     category_name: "Wraps",
  //     customizations: ["Extra Paneer", "Mint Sauce", "Whole Wheat Wrap"]
  //   },
  //   {
  //     name: "Mexican Burrito Bowl",
  //     description: "Rice, beans, chicken, salsa, guacamole, and cheese",
  //     image_url: "https://images.unsplash.com/photo-1571091655789-01a7a3788a32",
  //     price: 9.25,
  //     rating: 4.6,
  //     calories: 780,
  //     protein: 35,
  //     category_name: "Bowls",
  //     customizations: ["No Rice", "Extra Guacamole", "Spicy Salsa"]
  //   },
  //   {
  //     name: "Spicy Chicken Sandwich",
  //     description: "Fried chicken, spicy mayo, pickles, and lettuce",
  //     image_url: "https://images.unsplash.com/photo-1612197505153-8c3c0c4fc2f2",
  //     price: 8.75,
  //     rating: 4.5,
  //     calories: 820,
  //     protein: 30,
  //     category_name: "Sandwiches",
  //     customizations: ["Extra Mayo", "Grilled Instead of Fried", "No Pickles"]
  //   },
  //   {
  //     name: "Classic Margherita Pizza",
  //     description: "Tomato, mozzarella, fresh basil, and olive oil",
  //     image_url: "https://images.unsplash.com/photo-1601924821923-3ec0c4c28f5c",
  //     price: 11.0,
  //     rating: 4.7,
  //     calories: 850,
  //     protein: 24,
  //     category_name: "Pizzas",
  //     customizations: ["Extra Cheese", "Thin Crust", "No Basil"]
  //   },
  //   {
  //     name: "Protein Power Bowl",
  //     description: "Grilled chicken, quinoa, spinach, avocado, and chickpeas",
  //     image_url: "https://images.unsplash.com/photo-1578860390418-7cdb3f39fbdf",
  //     price: 10.0,
  //     rating: 4.8,
  //     calories: 700,
  //     protein: 40,
  //     category_name: "Bowls",
  //     customizations: ["Extra Protein", "No Avocado", "Add Boiled Egg"]
  //   },
  //   {
  //     name: "Paneer Burrito",
  //     description: "Paneer, rice, beans, and spicy Indian sauce",
  //     image_url: "https://images.unsplash.com/photo-1603079622822-cb84f36853f8",
  //     price: 8.5,
  //     rating: 4.4,
  //     calories: 680,
  //     protein: 29,
  //     category_name: "Wraps",
  //     customizations: ["Extra Paneer", "No Sauce", "Add Salsa"]
  //   },
  //   {
  //     name: "Chicken Club Sandwich",
  //     description: "Grilled chicken, bacon, lettuce, tomato, and mayo",
  //     image_url: "https://images.unsplash.com/photo-1599023722552-e01c4c2b5f77",
  //     price: 9.0,
  //     rating: 4.6,
  //     calories: 790,
  //     protein: 33,
  //     category_name: "Sandwiches",
  //     customizations: ["No Bacon", "Whole Wheat Bread", "Add Egg"]
  //   }
  // ]


  menu: [
    {
      name: "Classic Cheeseburger",
      description: "Beef patty, cheese, lettuce, tomato",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/044/844/600/large_2x/homemade-fresh-tasty-burger-with-meat-and-cheese-classic-cheese-burger-and-vegetable-ai-generated-free-png.png",
      price: 25.99,
      rating: 4.5,
      calories: 550,
      protein: 25,
      category_name: "Burgers",
      customizations: ["Extra Cheese", "Coke", "Fries", "Onions", "Bacon"],
    },
    {
      name: "Pepperoni Pizza",
      description: "Loaded with cheese and pepperoni slices",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/023/742/417/large_2x/pepperoni-pizza-isolated-illustration-ai-generative-free-png.png",
      price: 30.99,
      rating: 4.7,
      calories: 700,
      protein: 30,
      category_name: "Pizzas",
      customizations: [
        "Extra Cheese",
        "Jalapeños",
        "Garlic Bread",
        "Coke",
        "Olives",
      ],
    },
    {
      name: "Bean Burrito",
      description: "Stuffed with beans, rice, salsa",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/055/133/581/large_2x/deliciously-grilled-burritos-filled-with-beans-corn-and-fresh-vegetables-served-with-lime-wedge-and-cilantro-isolated-on-transparent-background-free-png.png",
      price: 20.99,
      rating: 4.2,
      calories: 480,
      protein: 18,
      category_name: "Burritos",
      customizations: ["Jalapeños", "Iced Tea", "Fries", "Salad"],
    },
    {
      name: "BBQ Bacon Burger",
      description: "Smoky BBQ sauce, crispy bacon, cheddar",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/060/236/245/large_2x/a-large-hamburger-with-cheese-onions-and-lettuce-free-png.png",
      price: 27.5,
      rating: 4.8,
      calories: 650,
      protein: 29,
      category_name: "Burgers",
      customizations: ["Onions", "Fries", "Coke", "Bacon", "Avocado"],
    },
    {
      name: "Chicken Caesar Wrap",
      description: "Grilled chicken, lettuce, Caesar dressing",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/048/930/603/large_2x/caesar-wrap-grilled-chicken-isolated-on-transparent-background-free-png.png",
      price: 21.5,
      rating: 4.4,
      calories: 490,
      protein: 28,
      category_name: "Wraps",
      customizations: ["Extra Cheese", "Coke", "Potato Wedges", "Tomatoes"],
    },
    {
      name: "Grilled Veggie Sandwich",
      description: "Roasted veggies, pesto, cheese",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/047/832/012/large_2x/grilled-sesame-seed-bread-veggie-sandwich-with-tomato-and-onion-free-png.png",
      price: 19.99,
      rating: 4.1,
      calories: 420,
      protein: 19,
      category_name: "Sandwiches",
      customizations: ["Mushrooms", "Olives", "Mozzarella Sticks", "Iced Tea"],
    },
    {
      name: "Double Patty Burger",
      description: "Two juicy beef patties and cheese",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/060/359/627/large_2x/double-cheeseburger-with-lettuce-tomatoes-cheese-and-sesame-bun-free-png.png",
      price: 32.99,
      rating: 4.9,
      calories: 720,
      protein: 35,
      category_name: "Burgers",
      customizations: [
        "Extra Cheese",
        "Onions",
        "Fries",
        "Coke",
        "Chicken Nuggets",
      ],
    },
    {
      name: "Paneer Tikka Wrap",
      description: "Spicy paneer, mint chutney, veggies",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/057/913/530/large_2x/delicious-wraps-a-tantalizing-array-of-wraps-filled-with-vibrant-vegetables-succulent-fillings-and-fresh-ingredients-artfully-arranged-for-a-mouthwatering-culinary-experience-free-png.png",
      price: 23.99,
      rating: 4.6,
      calories: 470,
      protein: 20,
      category_name: "Wraps",
      customizations: ["Jalapeños", "Tomatoes", "Salad", "Fries", "Iced Tea"],
    },
    {
      name: "Mexican Burrito Bowl",
      description: "Rice, beans, corn, guac, salsa",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/057/466/374/large_2x/healthy-quinoa-bowl-with-avocado-tomato-and-black-beans-ingredients-free-png.png",
      price: 26.49,
      rating: 4.7,
      calories: 610,
      protein: 24,
      category_name: "Bowls",
      customizations: ["Avocado", "Sweet Corn", "Salad", "Iced Tea"],
    },
    {
      name: "Spicy Chicken Sandwich",
      description: "Crispy chicken, spicy sauce, pickles",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/051/814/008/large_2x/a-grilled-chicken-sandwich-with-lettuce-and-tomatoes-free-png.png",
      price: 24.99,
      rating: 4.3,
      calories: 540,
      protein: 26,
      category_name: "Sandwiches",
      customizations: [
        "Jalapeños",
        "Onions",
        "Fries",
        "Coke",
        "Choco Lava Cake",
      ],
    },
    {
      name: "Classic Margherita Pizza",
      description: "Tomato, mozzarella, fresh basil",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/058/700/845/large_2x/free-isolated-on-transparent-background-delicious-pizza-topped-with-fresh-tomatoes-basil-and-melted-cheese-perfect-for-food-free-png.png",
      price: 26.99,
      rating: 4.1,
      calories: 590,
      protein: 21,
      category_name: "Pizzas",
      customizations: ["Extra Cheese", "Olives", "Coke", "Garlic Bread"],
    },
    {
      name: "Protein Power Bowl",
      description: "Grilled chicken, quinoa, veggies",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/056/106/379/large_2x/top-view-salad-with-chicken-avocado-tomatoes-and-lettuce-free-png.png",
      price: 29.99,
      rating: 4.8,
      calories: 580,
      protein: 38,
      category_name: "Bowls",
      customizations: ["Avocado", "Salad", "Sweet Corn", "Iced Tea"],
    },
    {
      name: "Paneer Burrito",
      description: "Paneer cubes, spicy masala, rice, beans",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/056/565/254/large_2x/burrito-with-cauliflower-and-vegetables-free-png.png",
      price: 24.99,
      rating: 4.2,
      calories: 510,
      protein: 22,
      category_name: "Burritos",
      customizations: ["Jalapeños", "Fries", "Garlic Bread", "Coke"],
    },
    {
      name: "Chicken Club Sandwich",
      description: "Grilled chicken, lettuce, cheese, tomato",
      image_url:
        "https://static.vecteezy.com/system/resources/previews/060/364/135/large_2x/a-flavorful-club-sandwich-with-turkey-bacon-and-fresh-vegetables-sliced-and-isolated-on-a-transparent-background-free-png.png",
      price: 27.49,
      rating: 4.5,
      calories: 610,
      protein: 31,
      category_name: "Sandwiches",
      customizations: ["Bacon", "Tomatoes", "Mozzarella Sticks", "Iced Tea"],
    },
  ],
};

export default dummyData;